### ISSUE TITLE
Проблема с автозагрузкой классов

### ISSUE THREAD

**Issue by ghost** [ElisDN/phpbb-integration-kit#1]
Модуль работает хорошо, но вот в случае не правильного ввода логина или пароля при логине пользователя выдается цела куча ошибок такого типа [phpBB Debug] PHP Warning: in file D:/server/domains/moda-plus.tt/framework/YiiBase.php on line 423: include(phpbb_captcha_factory.php): failed to open stream: No such file or directory

Я так понимаю что Yii пытается грузить классы phpbb. Сталкивались ли вы с такими ошибками и как их решить ???

**Comment by ghost** [comment]
Почему эта ошибка появилась у меня я уже понял. Это из-за того, что был превышено количество неправильных попыток входа от одного имени. Поставил в админке форума "0" и ошибки исчезли. А все из-за того, что добавляется проверка captcha

**Comment by ElisDN** [comment]
Да, кстати, там инклюдится простейший бутстрап из файлов форума. И именно чтобы ничего не мешалось нужно поотключать в форуме активацию аккаунта, капчу, антиспам и т.п.
